// Mocks generated by Mockito 5.4.2 from annotations
// in arkademi_test/test/mocks/api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:arkademi_test/data/api/courses_api.dart' as _i3;
import 'package:arkademi_test/domain/entities/entities.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCoursesStatus_0 extends _i1.SmartFake implements _i2.CoursesStatus {
  _FakeCoursesStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CoursesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoursesApi extends _i1.Mock implements _i3.CoursesApi {
  MockCoursesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CoursesStatus> getCoursesStatus() => (super.noSuchMethod(
        Invocation.method(
          #getCoursesStatus,
          [],
        ),
        returnValue: _i4.Future<_i2.CoursesStatus>.value(_FakeCoursesStatus_0(
          this,
          Invocation.method(
            #getCoursesStatus,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CoursesStatus>);
}
